AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  server

  Sample SAM Template for server

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 25

Resources:
  LoRoHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: loro-handler/
      Handler: loro-handler
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: "/{proxy+}"
            Method: ANY
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          REGION: "ap-northeast-1"
          MAIN_TABLE: "LoroMain"
  LoroMain:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: LoroMain
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: postedAt
          AttributeType: S
        - AttributeName: favorite
          AttributeType: S
        - AttributeName: following
          AttributeType: S
        - AttributeName: profile
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: userId-profile-Index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: profile
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: userId-following-Index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: following
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: userId-postedAt-Index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: postedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: userId-favorite-Index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: favorite
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LoRoHandlerAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  LoRoHandlerFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt LoRoHandlerFunction.Arn
  LoRoHandlerFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LoRoHandlerFunctionRole.Arn
  DynamoTableRoloMain:
    Description: "Main Dynamo Table ARN"
    Value: !GetAtt LoroMain.Arn
